language: java
jdk:
- openjdk17
env:
  global:
  - secure: DtkqopQGd4ov26U508KC5VpIV4SJWcqgj9T/jBHy+w9ZSMp40XFaOvw/88kZWL2P68gPDM8zZdl8c+kg3Ogxv31SlRytvjSHwS/xHO1pWq28yVZH8j/rhHb1iHocRsQywA+wG4aeCnJmVjn6Dm+PVDNzS7Ed4HeBp1CQYi5uf54=
  - secure: U+xUB1tfeLWQi9ye4rA8RCaQVn0x0aWKXJlk1zzBtSnm82iQOwqVfTg9rYL1ciGI3kIHk4QMQ/DtQ/9WJMyzz+I5dywZrGX6UCqprL368IeO+vB4lTK3nkCh0U2JBfh1bK6eRiFJ5GrqzyfQHMsVK0fzpmsnhRy5E7M6YmeOw/Q=
